from django.urls import path

from .views import (
    ActivityIngestAPI,
    CareerActivityUsersAPI,
    CareerEngagementUsersAPI,
    CareerReportAPI,
    CareerSwipeUsersAPI,
    CareersListAPI,
    CityUsersAPI,
    ConsentAPI,
    MyConnectionsAPI,
    CareerLeadUsersAPI,
    ConsentLeadsReportAPI,
    EventsListAPI,
    LeadEngagementUsersAPI,
    LocationEngagementUsersAPI,
    LikeVsSkipReportAPI,
    OverviewReportAPI,
    PopularByLocationReportAPI,
    CardClickUsersAPI,
    ProviderCardsAPI,
    ProviderCardUsersAPI,
    ProviderClicksReportAPI,
    CareerRouteUsersAPI,
    RouteClicksByCareerAPI,
    RouteClicksReportAPI,
    RouteEngagementUsersAPI,
    SearchedCareersReportAPI,
    SearchedCareerUsersAPI,
    SearchedCareerEngagementUsersAPI,
    SwipeDirectionUsersAPI,
    SwipeEngagementUsersAPI,
    TimeseriesReportAPI,
    TopCareersReportAPI,
    UserReportAPI,
    UsersListAPI,
    analytics_dashboard,
)

urlpatterns = [
    # ---- Public (frontend) ----
    path("activity/", ActivityIngestAPI.as_view(), name="analytics-activity"),
    path("consent/", ConsentAPI.as_view(), name="analytics-consent"),
    path("connections/", MyConnectionsAPI.as_view(), name="analytics-connections"),

    # ---- Admin dashboard (staff-only HTML page) ----
    path("dashboard/", analytics_dashboard, name="analytics-dashboard"),

    # ---- Admin reports (staff-only) ----
    path("admin/overview/", OverviewReportAPI.as_view(), name="analytics-overview"),
    path("admin/top/<str:activity_type>/", TopCareersReportAPI.as_view(), name="analytics-top"),
    path("admin/career-users/<str:activity_type>/", CareerEngagementUsersAPI.as_view(), name="analytics-career-users"),
    path("admin/career-users/<str:activity_type>/<int:career_id>/", CareerActivityUsersAPI.as_view(), name="analytics-career-activity-users"),
    path("admin/like-vs-skip/", LikeVsSkipReportAPI.as_view(), name="analytics-like-vs-skip"),
    path("admin/swipe-users/<int:career_id>/", CareerSwipeUsersAPI.as_view(), name="analytics-swipe-users"),
    path("admin/swipe-careers/", SwipeEngagementUsersAPI.as_view(), name="analytics-swipe-careers"),
    path("admin/swipe-direction/<str:direction>/", SwipeDirectionUsersAPI.as_view(), name="analytics-swipe-direction"),
    path("admin/routes/", RouteClicksReportAPI.as_view(), name="analytics-routes"),
    path("admin/routes-by-career/", RouteClicksByCareerAPI.as_view(), name="analytics-routes-by-career"),
    path("admin/route-users/<int:career_id>/", CareerRouteUsersAPI.as_view(), name="analytics-route-users"),
    path("admin/route-careers/", RouteEngagementUsersAPI.as_view(), name="analytics-route-careers"),
    path("admin/providers/", ProviderClicksReportAPI.as_view(), name="analytics-providers"),
    path("admin/provider-cards/", ProviderCardsAPI.as_view(), name="analytics-provider-cards"),
    path("admin/card-users/", CardClickUsersAPI.as_view(), name="analytics-card-users"),
    path("admin/provider-card-users/", ProviderCardUsersAPI.as_view(), name="analytics-provider-card-users"),
    path("admin/consent-leads/", ConsentLeadsReportAPI.as_view(), name="analytics-consent-leads"),
    path("admin/lead-users/<int:career_id>/", CareerLeadUsersAPI.as_view(), name="analytics-lead-users"),
    path("admin/lead-careers/", LeadEngagementUsersAPI.as_view(), name="analytics-lead-careers"),
    path("admin/timeseries/", TimeseriesReportAPI.as_view(), name="analytics-timeseries"),
    path("admin/by-location/", PopularByLocationReportAPI.as_view(), name="analytics-by-location"),
    path("admin/searched-careers/", SearchedCareersReportAPI.as_view(), name="analytics-searched-careers"),
    path("admin/searched-career-users/", SearchedCareerUsersAPI.as_view(), name="analytics-searched-career-users"),
    path("admin/searched-career-groups/", SearchedCareerEngagementUsersAPI.as_view(), name="analytics-searched-career-groups"),
    path("admin/city-users/", CityUsersAPI.as_view(), name="analytics-city-users"),
    path("admin/location-users/", LocationEngagementUsersAPI.as_view(), name="analytics-location-users"),
    path("admin/events/", EventsListAPI.as_view(), name="analytics-events"),
    path("admin/careers/", CareersListAPI.as_view(), name="analytics-careers"),
    path("admin/career/<int:career_id>/", CareerReportAPI.as_view(), name="analytics-career"),
    path("admin/users/", UsersListAPI.as_view(), name="analytics-users"),
    path("admin/user/<int:user_id>/", UserReportAPI.as_view(), name="analytics-user"),
]
