# Generated by Django 5.2.8 on 2026-01-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='pending_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='pending_plan_id',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='plan_id',
            field=models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='stripe_schedule_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
