# Generated by Django 5.2.8 on 2026-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_referralcode_referralcredit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('app_user_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='auto_renewing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='revenuecat_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='store',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='store_product_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
