# Generated by Django 5.2.8 on 2025-12-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fetch_careerjob',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CareerJobScrapeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fetch_jobscrapelog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('careers.careerjob',),
        ),
        migrations.CreateModel(
            name='UserSavedCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_id', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_links', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'pathzi_user_saved_career',
                'indexes': [models.Index(fields=['user_profile'], name='pathzi_user_user_pr_6a8bf2_idx'), models.Index(fields=['career_id'], name='pathzi_user_career__a0a892_idx')],
                'unique_together': {('user_profile', 'career_id')},
            },
        ),
    ]
