# Generated by Django 5.2.8 on 2025-12-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerScrapeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.UUIDField()),
                ('created_at', models.DateTimeField()),
                ('route', models.CharField(max_length=20)),
                ('sub_type', models.CharField(max_length=255)),
                ('job_slug', models.CharField(max_length=255)),
                ('job_url', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'fetch_jobscrapelog',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CareerJobScrapeLog',
        ),
    ]
