# Generated by Django 5.2.8 on 2026-01-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careerscrapelog_delete_careerjobscrapelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedcareer',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersavedcareer',
            name='report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersavedcareer',
            name='report_status',
            field=models.BooleanField(default=False),
        ),
    ]
