# Generated by Django 5.2.8 on 2026-03-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_coordinates_latitude_and_more'),
        ('careers', '0003_usersavedcareer_generated_at_usersavedcareer_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExploredCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explored_user_links', to='careers.career')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explored_career_links', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'career')},
            },
        ),
    ]
