# Generated by Django 5.2.8 on 2026-04-07 13:33

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_userexploredcareer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('source_text', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='all-MiniLM-L6-v2', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='careers.careerjob')),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='careers_car_updated_5f6554_idx')],
            },
        ),
    ]
