# Generated by Django 5.2.8 on 2026-04-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_careerembedding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerembedding',
            options={'managed': False},
        ),
    ]
