# Generated by Django 5.2.8 on 2026-04-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_alter_careerembedding_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='careerembedding',
            table='fetch_careerembedding',
        ),
    ]
