# Generated by Django 5.2.8 on 2026-04-23 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_alter_careerembedding_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavedcareer',
            name='career_id',
        ),
        migrations.AddField(
            model_name='usersavedcareer',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_user_links', to='careers.career'),
        ),
        migrations.AddField(
            model_name='usersavedcareer',
            name='old_career_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
