# Generated by Django 5.2.8 on 2026-04-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userembedding'),
        ('careers', '0008_remove_usersavedcareer_career_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usersavedcareer',
            name='pathzi_user_career__a0a892_idx',
        ),
        migrations.AlterUniqueTogether(
            name='usersavedcareer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='usersavedcareer',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_user_links', to='careers.career'),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedcareer',
            unique_together={('user_profile', 'career')},
        ),
        migrations.AddIndex(
            model_name='usersavedcareer',
            index=models.Index(fields=['career'], name='pathzi_user_career__a0a892_idx'),
        ),
    ]
