# Generated by Django 5.2.8 on 2026-04-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_remove_usersavedcareer_pathzi_user_career__a0a892_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedcareer',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_user_links', to='careers.career'),
        ),
    ]
