# Generated by Django 5.2.8 on 2026-04-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_alter_usersavedcareer_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersavedcareer',
            name='old_career_id',
        ),
    ]
