# Generated by Django 5.2.8 on 2026-09-11 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_passwordresetotp_attempts_reset_token'),
        ('careers', '0011_remove_usersavedcareer_old_career_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCareerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_status', models.BooleanField(default=False)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reports', to='careers.career')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_reports', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'pathzi_user_career_report',
                'unique_together': {('user_profile', 'career')},
            },
        ),
    ]
