# Generated by Django 5.2.8 on 2026-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userprofile_referral_access_until_and_more'),
        ('careers', '0013_copy_saved_career_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercareerreport',
            name='profile_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='usercareerreport',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usercareerreport',
            name='user_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='usercareerreport',
            index=models.Index(fields=['user_profile', 'user_saved', '-updated_at'], name='pathzi_user_user_pr_2b5849_idx'),
        ),
    ]
