# Generated by Django 5.2.8 on 2025-12-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_userprofile_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200)),
                ('job_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('salary', models.IntegerField(null=True)),
                ('user_profile', models.ManyToManyField(blank=True, related_name='jobs', to='accounts.userprofile')),
            ],
        ),
    ]
