# Generated by Django 5.2.8 on 2025-12-26 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_status'),
        ('jobs', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='DwpJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('subcategory', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('job_url', models.URLField(blank=True, default='', max_length=1000)),
                ('apply_url', models.URLField(blank=True, default='', max_length=1000)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('posting_date', models.CharField(blank=True, default='', max_length=255)),
                ('closing_date', models.CharField(blank=True, default='', max_length=255)),
                ('hours', models.CharField(blank=True, default='', max_length=255)),
                ('job_type', models.CharField(blank=True, default='', max_length=255)),
                ('job_reference', models.CharField(blank=True, default='', max_length=255)),
                ('salary', models.CharField(blank=True, default='', max_length=255)),
                ('remote_working', models.CharField(blank=True, default='', max_length=255)),
                ('additional_salary_information', models.TextField(blank=True, default='')),
                ('disability_confident', models.BooleanField(default=False)),
                ('listing_snippet', models.TextField(blank=True, default='')),
                ('summary_intro', models.TextField(blank=True, default='')),
                ('summary_bullets', models.TextField(blank=True, default='')),
                ('what_youll_do', models.TextField(blank=True, default='')),
                ('skills_youll_need', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('scraped_at', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_scrape_message', models.TextField(blank=True, default='')),
                ('last_scrape_run_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'job_dwpjob',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobScrapeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('subcategory', models.CharField(blank=True, default='', max_length=255)),
                ('start_url', models.URLField(blank=True, default='', max_length=1000)),
                ('job_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'job_jobscrapelog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_links', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'pathzi_user_saved_job',
            },
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.AddIndex(
            model_name='usersavedjob',
            index=models.Index(fields=['user_profile'], name='pathzi_user_user_pr_cd4deb_idx'),
        ),
        migrations.AddIndex(
            model_name='usersavedjob',
            index=models.Index(fields=['job_id'], name='pathzi_user_job_id_76bc3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedjob',
            unique_together={('user_profile', 'job_id')},
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('jobs.dwpjob',),
        ),
    ]
