"""
Django settings for pathzi project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# REQUIRED in the environment. Signs password-reset links, sessions and
# anything else Django signs.
# No default, deliberately. The old key is public - it was committed to git
# from the first commit - so leaving it as a fallback would mean any
# environment that forgot to set SECRET_KEY would silently keep using a key
# anyone can read. Better to refuse to start.
SECRET_KEY = config("SECRET_KEY")

# Defaults to OFF. DEBUG=True leaks settings, SQL and stack traces to anyone
# who triggers an error, and it was hard-coded on. Development sets
# DEBUG=True in .env.
DEBUG = config("DEBUG", default=False, cast=bool)

# HTTPS hardening. All of these switch on whenever DEBUG is off, so
# production gets them and local development is untouched. Each can still be
# overridden individually if a deploy needs it.
#   SSL redirect        - http:// requests are bounced to https://
#   Secure cookies      - the session and CSRF cookies never travel in clear
#   HSTS                - browsers refuse http:// for this domain for a year
# HSTS is the one to be careful with: once a browser has seen it, it will not
# talk to this domain over http for that long, so only enable it when the
# certificate is known good. Preload is deliberately left off.
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=not DEBUG, cast=bool)

SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=(31536000 if not DEBUG else 0), cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG, cast=bool)
SECURE_HSTS_PRELOAD = False

# DigitalOcean terminates TLS before the app, so without this Django sees
# plain http and SECURE_SSL_REDIRECT would loop forever.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

import ssl

REDIS_URL = config("REDIS_URL")

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_RATES": {
        "user": "100/min",
        "interaction": "10/second",
        # Frontend analytics ingest: each request can carry up to 200 events,
        # so a modest request rate still allows a high event throughput.
        "analytics": "120/min",
    }
}

# ALLOWED_HOSTS = ["*"]

ALLOWED_HOSTS = [
    "stingray-app-jqmc6.ondigitalocean.app",
    "pathzi.co.uk",
    "www.pathzi.co.uk",
    "localhost"
]


# Django cache uses clean REDIS_URL + Python SSL option
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "ssl_cert_reqs": ssl.CERT_NONE,
            },
        },
    }
}


# Celery needs ssl_cert_reqs in the rediss URL
CELERY_REDIS_URL = f"{REDIS_URL}/0?ssl_cert_reqs=CERT_NONE"

CELERY_BROKER_URL = CELERY_REDIS_URL
CELERY_RESULT_BACKEND = CELERY_REDIS_URL

CELERY_BROKER_USE_SSL = {
    "ssl_cert_reqs": ssl.CERT_NONE,
}

CELERY_REDIS_BACKEND_USE_SSL = {
    "ssl_cert_reqs": ssl.CERT_NONE,
}

CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 240

# ---------------------------------------------------------------------------
# Redis-command reduction ("Layer 2" tweaks).
# Redis is the Celery broker + result backend, so a running worker keeps
# clicking the Upstash command meter even with no users. These cut the
# always-on idle chatter without changing task behaviour.
# ---------------------------------------------------------------------------

# Don't write a result receipt to Redis for every task (we never read them).
CELERY_TASK_IGNORE_RESULT = True

# Silence inter-worker gossip / heartbeat / remote-control polling — we run a
# single worker and don't use Flower-style monitoring or remote commands.
CELERY_WORKER_SEND_TASK_EVENTS = False
CELERY_WORKER_ENABLE_REMOTE_CONTROL = False

# Check the broker for scheduled/delayed tasks less often when idle.
# Trade-off: a delayed task may start up to ~5s late (fine for background work).
CELERY_BROKER_TRANSPORT_OPTIONS = {"polling_interval": 5.0}

# How long analytics events are kept before the retention purge deletes them.
ANALYTICS_RETENTION_DAYS = 365

# Periodic tasks (requires beat: `celery -A pathzi worker -B`)
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "flush-analytics-queue": {
        # Drains frontend-fired events from the analytics:queue Redis list
        # into Postgres in batches (Lane B of the analytics module).
        "task": "analytics.tasks.flush_activity_queue",
        # 30s instead of 5s → 6x fewer idle Redis polls. Events still land
        # within ~30s, which is well within "appears in seconds".
        "schedule": 30.0,
    },
    "purge-old-analytics": {
        # GDPR/storage hygiene: delete events older than ANALYTICS_RETENTION_DAYS.
        "task": "analytics.tasks.purge_old_activity",
        "schedule": crontab(hour=3, minute=0),  # daily at 03:00
    },
}
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'qualification',
    'courses',
    'jobs',
    'apprenticeship',
    'careers',
    "billing",
    "django_extensions",
    "geo_search",
    "usage_limits",
    "analytics",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pathzi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        # JWTAuthentication plus revocation - see accounts/authentication.py.
        # Behaves identically unless a user has signed out everywhere.
        "accounts.authentication.RevocableJWTAuthentication",
    ],
    # Same JSON, but the Content-Type says charset=utf-8 rather than
    # leaving the client to assume it.
    "DEFAULT_RENDERER_CLASSES": [
        "pathzi.renderers.Utf8JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    # Fails open when Redis is down, instead of 500ing every endpoint before
    # the view runs - see pathzi/throttling.py.
    "DEFAULT_THROTTLE_CLASSES": [
        "pathzi.throttling.ResilientUserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "10/min",
        "interaction": "10/second",
        # Frontend analytics ingest: each request carries up to 200 events,
        # so a modest request rate still allows high event throughput.
        "analytics": "120/min",
        # Password-reset code/token guesses (accounts.throttles).
        "otp_ip": "30/hour",
        "otp_email": "10/hour",
    },
    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 50,
}

if DEBUG:
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"].insert(
        0, "rest_framework.authentication.SessionAuthentication"
    )

WSGI_APPLICATION = 'pathzi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

import dj_database_url
from decouple import config

DATABASE_URL = config("DATABASE_URL")  # reads from .env or system env

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,  # Increased from 60 to 600 for better connection pooling
        ssl_require=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Optimized for performance - removed CommonPasswordValidator which loads a large file
# and adds ~2-3 seconds to password hashing operations
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    # CommonPasswordValidator removed - it loads a 3MB file of common passwords
    # which adds 2-3 seconds to every password hash operation
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID")
GOOGLE_WEB_CLIENT_ID=config("GOOGLE_WEB_CLIENT_ID")
GOOGLE_ANDROID_CLIENT_ID=config("GOOGLE_ANDROID_CLIENT_ID")
GOOGLE_IOS_CLIENT_ID=config("GOOGLE_IOS_CLIENT_ID")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = config("GOOGLE_REDIRECT_URI")
APPLE_REDIRECT_URI = config("APPLE_REDIRECT_URI")
GEOAPIFY_API_KEY = config("GEOAPIFY_API_KEY")
GEOAPIFY_DEFAULT_COUNTRY = config("GEOAPIFY_DEFAULT_COUNTRY")

# RevenueCat (Part 2 payments). Both default to empty so the app still boots
# before the keys are in place - the webhook and refresh endpoints check for
# them and refuse politely rather than the whole site failing to start.
REVENUECAT_SECRET_KEY = config("REVENUECAT_SECRET_KEY", default="")
REVENUECAT_WEBHOOK_SECRET = config("REVENUECAT_WEBHOOK_SECRET", default="")

# HMAC signing secret - separate from the Authorization header value above.
# Verifies X-RevenueCat-Webhook-Signature so a leaked header value alone is
# not enough to forge a payment event.
REVENUECAT_SIGNING_SECRET = config("REVENUECAT_SIGNING_SECRET", default="")

# Which RevenueCat project we talk to, and the entitlement that means
# "this user has paid". Both are visible in the dashboard.
REVENUECAT_PROJECT_ID = config("REVENUECAT_PROJECT_ID", default="")
REVENUECAT_ENTITLEMENT_ID = config("REVENUECAT_ENTITLEMENT_ID", default="pathzi_pro")

# Free tier after the trial. OFF by default on purpose: the current live app
# has no paywall screen and no way to subscribe, so switching this on before
# the new app ships would strand existing users with a shrunken home screen.
# Turn on (PAYWALL_ENFORCED=True in the environment) the day the new app goes live.
PAYWALL_ENFORCED = config("PAYWALL_ENFORCED", default=False, cast=bool)

# Gemini, used only by the offline data-backfill scripts (never in a request).
GEMINI_API_KEY = config("GEMINI_API_KEY", default="")
GEMINI_MODEL = config("GEMINI_MODEL", default="gemini-2.5-flash")

# Email goes out through Resend's SMTP relay (moved from SendGrid 2026-09-22).
# Plain SMTP, so every send_mail() call is unchanged. Host, user and port are
# read from the environment so switching provider again is an .env change:
# for SendGrid it would be EMAIL_HOST=smtp.sendgrid.net, EMAIL_HOST_USER=apikey.
#
# RESEND_API_KEY defaults to empty on purpose. Without a key, emails fail
# (password reset, invites) - but the app still starts. Making it required
# would take the whole API down on a deploy that forgot to set it.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="smtp.resend.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="resend")  # literally "resend"
EMAIL_HOST_PASSWORD = config("RESEND_API_KEY", default="")
# Must be an address on a domain verified in Resend, or Resend refuses it.
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
EMAIL_TIMEOUT = 30  # Prevent indefinite hangs on SMTP connections

APPLE_CLIENT_ID = config("APPLE_CLIENT_ID")
APPLE_CLIENT_ID_FLUTTER = config("APPLE_CLIENT_ID_FLUTTER")




# This is the stripe data check it out.
import os

# Stripe settings (use python-decouple so it reads from .env)
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default=None)
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default=None)

# Use a real Stripe API version format like 2023-10-16 (keep yours if you intentionally set it)
STRIPE_API_VERSION = config("STRIPE_API_VERSION", default="2023-10-16")

BILLING_RETURN_URL = config("BILLING_RETURN_URL", default="http://localhost:3000/account")

STRIPE_PRICE_ID_MONTHLY = config("STRIPE_PRICE_ID_MONTHLY", default=None)
STRIPE_PRICE_ID_QUARTERLY = config("STRIPE_PRICE_ID_QUARTERLY", default=None)
STRIPE_PRICE_ID_YEARLY = config("STRIPE_PRICE_ID_YEARLY", default=None)

STRIPE_PLANS = {
    "monthly":   {"price_id": STRIPE_PRICE_ID_MONTHLY},
    "quarterly": {"price_id": STRIPE_PRICE_ID_QUARTERLY},
    "yearly":    {"price_id": STRIPE_PRICE_ID_YEARLY},
}



CSRF_TRUSTED_ORIGINS = [
    "https://stingray-app-jqmc6.ondigitalocean.app",
    "http://localhost:8002",
    "http://127.0.0.1:8002",
]

import os

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "simple": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "debug.log"),
            "formatter": "simple",
        },
    },

    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=3),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,

    # Refuses refresh tokens from ended sessions (sign out other devices,
    # password change, password reset). The stock serializer skipped that
    # check, so an ended device could refresh its way back in.
    "TOKEN_REFRESH_SERIALIZER": "accounts.token_refresh.RevocableTokenRefreshSerializer",

    # Tokens are signed with their OWN key, which defaults to SECRET_KEY so
    # nothing changes today. The point is what it makes possible later:
    # SimpleJWT signs with SECRET_KEY by default, so rotating the leaked
    # SECRET_KEY would invalidate every token and log out every user on
    # every device at once. With JWT_SIGNING_KEY set separately, SECRET_KEY
    # can be rotated without touching anyone's session.
    # Deliberately NOT SECRET_KEY. Tokens already on users' phones were
    # signed with the old key, so that value lives on here and they keep
    # working, while SECRET_KEY itself has been replaced. Rotating this one
    # logs everybody out, so it is a maintenance-window job.
    "SIGNING_KEY": config("JWT_SIGNING_KEY", default=SECRET_KEY),
}




# --- Analytics dashboard auth ---
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
