"""
Django settings for pathzi project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-phnpwqr^o#9fgr&8w0w&a3&ypw-%+y1^+ft=*l8ywn9*2-u(gx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'qualification',
    'courses',
    'jobs',
    'apprenticeship',
    'careers',
    "billing",
    "django_extensions",
    "geo_search",
    "usage_limits"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pathzi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "10/min"
    },
    # "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 50,
}

if DEBUG:
    REST_FRAMEWORK["DEFAULT_AUTHENTICATION_CLASSES"].insert(
        0, "rest_framework.authentication.SessionAuthentication"
    )

WSGI_APPLICATION = 'pathzi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

import dj_database_url
from decouple import config

DATABASE_URL = config("DATABASE_URL")  # reads from .env or system env

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,  # Increased from 60 to 600 for better connection pooling
        ssl_require=True,
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Optimized for performance - removed CommonPasswordValidator which loads a large file
# and adds ~2-3 seconds to password hashing operations
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    # CommonPasswordValidator removed - it loads a 3MB file of common passwords
    # which adds 2-3 seconds to every password hash operation
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID")
GOOGLE_WEB_CLIENT_ID=config("GOOGLE_WEB_CLIENT_ID")
GOOGLE_ANDROID_CLIENT_ID=config("GOOGLE_ANDROID_CLIENT_ID")
GOOGLE_IOS_CLIENT_ID=config("GOOGLE_IOS_CLIENT_ID")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = config("GOOGLE_REDIRECT_URI")
APPLE_REDIRECT_URI = config("APPLE_REDIRECT_URI")
GEOAPIFY_API_KEY = config("GEOAPIFY_API_KEY")
GEOAPIFY_DEFAULT_COUNTRY = config("GEOAPIFY_DEFAULT_COUNTRY")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "apikey"  # literally this!
EMAIL_HOST_PASSWORD = config("SENDGRID_API_KEY")  # your API key
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
EMAIL_TIMEOUT = 30  # Prevent indefinite hangs on SMTP connections

APPLE_CLIENT_ID = config("APPLE_CLIENT_ID")




# This is the stripe data check it out.
import os

# Stripe settings (use python-decouple so it reads from .env)
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default=None)
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default=None)

# Use a real Stripe API version format like 2023-10-16 (keep yours if you intentionally set it)
STRIPE_API_VERSION = config("STRIPE_API_VERSION", default="2023-10-16")

BILLING_RETURN_URL = config("BILLING_RETURN_URL", default="http://localhost:3000/account")

STRIPE_PRICE_ID_MONTHLY = config("STRIPE_PRICE_ID_MONTHLY", default=None)
STRIPE_PRICE_ID_QUARTERLY = config("STRIPE_PRICE_ID_QUARTERLY", default=None)
STRIPE_PRICE_ID_YEARLY = config("STRIPE_PRICE_ID_YEARLY", default=None)

STRIPE_PLANS = {
    "monthly":   {"price_id": STRIPE_PRICE_ID_MONTHLY},
    "quarterly": {"price_id": STRIPE_PRICE_ID_QUARTERLY},
    "yearly":    {"price_id": STRIPE_PRICE_ID_YEARLY},
}



CSRF_TRUSTED_ORIGINS = [
    "https://stingray-app-jqmc6.ondigitalocean.app",
    "http://localhost:8002",
    "http://127.0.0.1:8002",
]

import os

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "simple": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "debug.log"),
            "formatter": "simple",
        },
    },

    "root": {
        "handlers": ["console", "file"],
        "level": "INFO",
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=3),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
}


