# Generated by Django 5.2.8 on 2026-06-11 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0011_remove_usersavedcareer_old_career_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, default='', max_length=255)),
                ('provider_type', models.CharField(blank=True, default='', max_length=64)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('consent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_leads', to='careers.career')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_provider_lead',
                'ordering': ('-consent_at',),
                'indexes': [models.Index(fields=['provider_name'], name='analytics_p_provide_6403ff_idx'), models.Index(fields=['user', 'consent_at'], name='analytics_p_user_id_15775c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField(blank=True, null=True)),
                ('activity_type', models.CharField(db_index=True, max_length=50)),
                ('activity_value', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='careers.career')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_user_activity',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['activity_type', 'created_at'], name='analytics_u_activit_4de4fb_idx'), models.Index(fields=['career', 'activity_type'], name='analytics_u_career__ab54e6_idx'), models.Index(fields=['user', 'activity_type'], name='analytics_u_user_id_fab10a_idx'), models.Index(fields=['user', 'career', 'activity_type'], name='analytics_u_user_id_9be21f_idx')],
            },
        ),
    ]
