# Generated by Django 5.2.8 on 2026-06-22 11:59

from django.db import migrations, models


def seed_route_types(apps, schema_editor):
    """
    route_id changed from an integer id to a route TYPE string. Backfill the
    existing route_clicked/route_viewed rows (which now hold "1".."6") with a
    deterministic course/apprenticeship/job value so the new per-career report
    has data to show. Distributes by the old numeric id (no randomness so the
    migration is reproducible).
    """
    UserActivity = apps.get_model("analytics", "UserActivity")
    route_types = ("course", "apprenticeship", "job")
    qs = UserActivity.objects.filter(
        activity_type__in=("route_clicked", "route_viewed")
    ).exclude(route_id__isnull=True).exclude(route_id="")
    for row in qs.only("id", "route_id").iterator():
        try:
            n = int(row.route_id)
        except (TypeError, ValueError):
            continue  # already a route-type string — leave it
        row.route_id = route_types[n % len(route_types)]
        row.save(update_fields=["route_id"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='route_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(seed_route_types, noop),
    ]
