# Generated by Django 5.2.8 on 2026-06-22 13:38

from django.db import migrations, models


# Dummy card titles per route type, used to backfill existing provider-link
# clicks so the new "by title" report has data to show.
_TITLES = {
    "course": [
        "BSc (Hons) Programme", "Level 3 BTEC Diploma", "Foundation Degree",
        "HND Course", "Undergraduate Certificate",
    ],
    "apprenticeship": [
        "Level 2 Intermediate Apprenticeship", "Level 3 Advanced Apprenticeship",
        "Degree Apprenticeship", "Higher Apprenticeship",
    ],
    "job": [
        "Graduate Trainee Role", "Junior Associate Position",
        "Entry-Level Vacancy", "Apprentice Assistant Job",
    ],
}
_ROUTES = ("course", "apprenticeship", "job")


def seed_cards(apps, schema_editor):
    """Backfill route_id + a card title on existing provider/connect clicks."""
    UserActivity = apps.get_model("analytics", "UserActivity")
    qs = UserActivity.objects.filter(
        activity_type__in=("provider_link_clicked", "connect_button_clicked"),
        card__isnull=True,
    )
    for i, row in enumerate(qs.only("id", "route_id", "card").iterator()):
        route = _ROUTES[i % len(_ROUTES)]
        titles = _TITLES[route]
        row.route_id = route
        row.card = titles[i % len(titles)]
        row.save(update_fields=["route_id", "card"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_useractivity_route_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='card',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(seed_cards, noop),
    ]
