# Generated by Django 5.2.8 on 2026-07-20 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_useractivity_card'),
        ('careers', '0011_remove_usersavedcareer_old_career_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerlead',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='providerlead',
            name='card_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='providerlead',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='providerlead',
            name='consented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerlead',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='providerlead',
            name='route_item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerlead',
            name='route_type',
            field=models.CharField(blank=True, choices=[('course', 'Course'), ('apprenticeship', 'Apprenticeship'), ('job', 'Job')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='providerlead',
            name='salary_or_cost',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='providerlead',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='providerlead',
            index=models.Index(fields=['route_type', 'route_item_id'], name='analytics_p_route_t_891ec0_idx'),
        ),
    ]
