# Generated by Django 5.2.8 on 2025-12-26 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprenticeshipScrapeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.UUIDField()),
                ('created_at', models.DateTimeField()),
                ('category', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('start_url', models.CharField(max_length=1000)),
                ('vacancy_ref', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'apprenticeship_apprenticeshipscrapelog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApprenticeshipVacancy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vacancy_ref', models.CharField(max_length=32, unique=True)),
                ('vacancy_url', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=255)),
                ('subcategory', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('employer_name', models.CharField(max_length=500)),
                ('location_summary', models.CharField(max_length=255)),
                ('closing_text', models.CharField(max_length=255)),
                ('posted_text', models.CharField(max_length=255)),
                ('summary_text', models.TextField()),
                ('wage', models.CharField(max_length=255)),
                ('wage_extra', models.TextField()),
                ('training_course', models.CharField(max_length=500)),
                ('hours', models.CharField(max_length=500)),
                ('hours_per_week', models.CharField(max_length=64)),
                ('start_date', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('positions_available', models.CharField(max_length=64)),
                ('work_intro', models.TextField()),
                ('what_youll_do_heading', models.CharField(max_length=255)),
                ('what_youll_do_items', models.TextField()),
                ('where_youll_work_name', models.CharField(max_length=500)),
                ('where_youll_work_address', models.TextField()),
                ('training_intro', models.TextField()),
                ('training_provider', models.CharField(max_length=500)),
                ('training_course_repeat', models.CharField(max_length=500)),
                ('what_youll_learn_items', models.TextField()),
                ('training_schedule', models.TextField()),
                ('more_training_information', models.TextField()),
                ('essential_qualifications', models.TextField()),
                ('skills_items', models.TextField()),
                ('other_requirements_items', models.TextField()),
                ('about_employer', models.TextField()),
                ('employer_website', models.CharField(max_length=1000)),
                ('company_benefits_items', models.TextField()),
                ('after_this_apprenticeship', models.TextField()),
                ('contact_name', models.CharField(max_length=500)),
                ('scraped_at', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_status', models.CharField(max_length=20)),
                ('last_scrape_message', models.TextField()),
                ('last_scrape_run_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apprenticeship_apprenticeshipvacancy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apprenticeship',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apprenticeship.apprenticeshipvacancy',),
        ),
        migrations.CreateModel(
            name='UserSavedApprenticeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_ref', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apprenticeship_links', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'pathzi_user_saved_apprenticeship',
                'indexes': [models.Index(fields=['user_profile'], name='pathzi_user_user_pr_83ed7b_idx'), models.Index(fields=['vacancy_ref'], name='pathzi_user_vacancy_a22c09_idx')],
                'unique_together': {('user_profile', 'vacancy_ref')},
            },
        ),
    ]
