# Generated by Django 5.2.8 on 2025-12-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_qualification_userprofile_amount_to_earn_and_more'),
        ('qualification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualification.qualification'),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
