# Generated by Django 5.2.8 on 2025-12-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_qualification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='interest',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='career_switcher',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='amount_to_earn',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='preference',
            new_name='discipline',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='study_level',
            new_name='education_level',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='study_mediam',
            new_name='zip_code',
        ),
    ]
