# Generated by Django 5.2.8 on 2025-12-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_category_alter_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
    model_name='userprofile',
    name='city',
    field=models.CharField(max_length=200, blank=True, null=True),
),
    ]
