# Generated by Django 5.2.8 on 2025-12-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
