# Generated by Django 5.2.8 on 2026-01-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='report',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='report_status',
            field=models.BooleanField(default=False),
        ),
    ]
