# Generated by Django 5.2.8 on 2026-01-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_coordinates'),
        ('accounts', '0017_userprofile_lat_userprofile_lng'),
    ]

    operations = [
    ]
