# Generated by Django 5.2.8 on 2026-01-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20260127_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
