# Generated by Django 5.2.8 on 2026-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_coordinates_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
