# Generated by Django 5.2.8 on 2026-03-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_userprofile_apple_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_apple_private_email',
            field=models.BooleanField(default=False),
        ),
    ]
