# Generated by Django 5.2.8 on 2026-07-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qualification',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
