# Generated by Django 5.2.8 on 2026-09-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_userprofile_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('parent_guardian', 'Parent or Guardian'), ('career_changer', 'Career Changer'), ('reskilling', 'Reskilling / Upskilling')], max_length=32, null=True),
        ),
    ]
