# Generated by Django 5.2.8 on 2026-09-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_passwordresetotp_attempts_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
