# Generated by Django 5.2.8 on 2026-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_fill_account_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_days_banked',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
