# Generated by Django 5.2.8 on 2026-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_userprofile_referral_access_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokens_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
