# Generated by Django 5.2.8 on 2025-12-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_userprofile_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=200)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('course_duration', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('fee', models.IntegerField(null=True)),
                ('user_profile', models.ManyToManyField(blank=True, null=True, related_name='courses', to='accounts.userprofile')),
            ],
        ),
    ]
