# Generated by Django 5.2.8 on 2025-12-26 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_userprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseScrapeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField()),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('keyword', models.CharField(blank=True, default='', max_length=255)),
                ('postcode', models.CharField(blank=True, default='', max_length=64)),
                ('distance', models.IntegerField(default=0)),
                ('start_url', models.URLField(blank=True, default='', max_length=1000)),
                ('course_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(default='', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'course_coursescrapelog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NcsCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_id', models.UUIDField(unique=True)),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('subcategory', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('course_url', models.URLField(max_length=1000)),
                ('course_name', models.CharField(blank=True, default='', max_length=500)),
                ('course_type', models.CharField(blank=True, default='', max_length=500)),
                ('learning_method', models.CharField(blank=True, default='', max_length=255)),
                ('course_hours', models.CharField(blank=True, default='', max_length=255)),
                ('course_stryd_time', models.CharField(blank=True, default='', max_length=255)),
                ('course_qualification_level', models.CharField(blank=True, default='', max_length=255)),
                ('course_description', models.TextField(blank=True, default='')),
                ('attendance_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('awarding_organization', models.CharField(blank=True, default='', max_length=500)),
                ('who_this_course_is_for', models.TextField(blank=True, default='')),
                ('entry_reeq', models.TextField(blank=True, default='')),
                ('college_name', models.CharField(blank=True, default='', max_length=500)),
                ('address', models.TextField(blank=True, default='')),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.URLField(blank=True, default='', max_length=1000)),
                ('duration', models.CharField(blank=True, default='', max_length=255)),
                ('cost', models.CharField(blank=True, default='', max_length=255)),
                ('cost_description', models.TextField(blank=True, default='')),
                ('scraped_at', models.DateTimeField()),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_scrape_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_scrape_message', models.TextField(blank=True, default='')),
                ('last_scrape_run_id', models.UUIDField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'course_ncscourse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.ncscourse',),
        ),
        migrations.CreateModel(
            name='UserSavedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'pathzi_user_saved_course',
                'indexes': [models.Index(fields=['user_profile'], name='pathzi_user_user_pr_9d0cc2_idx'), models.Index(fields=['course_id'], name='pathzi_user_course__7275ac_idx')],
                'unique_together': {('user_profile', 'course_id')},
            },
        ),
    ]
