# Generated by Django 5.2.8 on 2025-12-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_qualification_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user_profile',
            field=models.ManyToManyField(blank=True, related_name='courses', to='accounts.userprofile'),
        ),
    ]
