# Generated by Django 5.2.8 on 2025-12-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qulification_type', models.CharField(blank=True, max_length=200)),
                ('subjects', models.CharField(blank=True, max_length=200)),
                ('Grades', models.CharField(blank=True, max_length=50)),
                ('completion_year', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
