# Generated by Django 5.2.8 on 2025-12-08 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_qualification_and_more'),
        ('qualification', '0002_rename_grades_qualification_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='accounts.userprofile'),
        ),
    ]
